package List;
public class Main {
    public static void main(String[] args) {

        /* ---------------------------- Singly linked list test cases ---------------------------- */
//        SinglyLinkedList <Character> list = new SinglyLinkedList<>();
//        System.out.println("Before adding eny element");
//        System.out.println("capacity : " + list.capacity());
//        System.out.println("Is empty : " + list.isEmpty());
//        list.display();
//        System.out.println("----------------------------");
//        System.out.println("---> Insertion <---");
//        System.out.println("Add 5 elements from begin");
//        list.insertFirst('A');
//        list.insertFirst('B');
//        list.insertFirst('C');
//        list.insertFirst('D');
//        list.insertFirst('E');
//        System.out.println("Add 5 elements from end");
//        list.insert('a');
//        list.insert('b');
//        list.insert('c');
//        list.insert('d');
//        list.insert('e');
//        System.out.println("Add 3 elements in specific indexes");
//        System.out.println("Insert '@' in index 2");
//        list.insert(2, '@');
//        System.out.println("Insert '$' in index 5");
//        list.insert(5, '$');
//        System.out.println("Insert '%' in index 7");
//        list.insert(7, '%');
//        System.out.println("capacity : " + list.capacity());
//        System.out.println("Is empty : " + list.isEmpty());
//        list.display();
//        System.out.println("After reverse list");
//        list.reverse();
//        list.display();
//        System.out.println("----------------------------");
//        System.out.println("---> Update <---");
//        System.out.println("Update index 2 to 'Z'");
//        list.update(2, 'Z');
//        System.out.println("Update index 8 to 'x'");
//        list.update(8, 'x');
//        list.display();
//        System.out.println("----------------------------");
//        System.out.println("---> Removal <---");
//        System.out.println("Remove index 3");
//        list.remove(3);
//        System.out.println("Remove last two elements ans first three");
//        list.pop();
//        list.pop();
//        list.remove();
//        list.remove();
//        list.remove();
//        System.out.println("capacity : " + list.capacity());
//        list.display();
//        System.out.println("----------------------------");
//        System.out.println("---> Clear <---");
//        System.out.println("Clear the list");
//        list.clear();
//        System.out.println("capacity : " + list.capacity());
//        System.out.println("Is empty : " + list.isEmpty());
//        list.display();


        /* ---------------------------- Doubly linked list test cases ---------------------------- */
//        DoublyLinkedList <String> list = new DoublyLinkedList<>();
//        System.out.println("Before adding any elements");
//        System.out.println("Is empty : " + list.isEmpty());
//        System.out.println("Size : " + list.capacity());
//        list.display(true);
//        System.out.println("---> Insertion <---");
//        System.out.println("Add 3 elements from begin");
//        list.insertFirst("Begin 1");
//        list.insertFirst("Begin 2");
//        list.insertFirst("Begin 3");
//        System.out.println("Add 3 elements from end");
//        list.insert("End 1");
//        list.insert("End 2");
//        list.insert("End 3");
//        System.out.println("Add 'Specific 1' in index 1");
//        list.insert(1, "Specific 1");
//        System.out.println("Add 'Specific 2' in index 4");
//        list.insert(4, "Specific 2");
//        System.out.println("Print in asc order");
//        list.display(true);
//        System.out.println("Print in desc order");
//        list.display(false);
//        System.out.println("Is empty : " + list.isEmpty());
//        System.out.println("Size : " + list.capacity());
//        System.out.println("----------------------------");
//        System.out.println("---> Search <---");
//        System.out.println("'Specific 1' in index " + list.search("Specific 1"));
//        System.out.println("'Begin 3' in index " + list.search("Begin 3"));
//        System.out.println("'End 5' in index " + list.search("End 5"));
//        System.out.println("----------------------------");
//        System.out.println("---> Access <---");
//        System.out.println("Element in index 2 is : " + list.get(2));
//        System.out.println("Element in index 7 is : " + list.get(7));
//        System.out.println("Element in index 15 is : " + list.get(15));
//        System.out.println("----------------------------");
//        System.out.println("---> Update <---");
//        System.out.println("Update element in index 3 to 'Updated 1'");
//        list.update(3, "Updated 1");
//        System.out.println("Element in index 3 is : " + list.get(3));
//        System.out.println("Update element in index 7 to 'Updated 2'");
//        list.update(7, "Updated 2");
//        System.out.println("Element in index 7 is : " + list.get(7));
//        System.out.println("----------------------------");
//        System.out.println("---> Reverse <---");
//        System.out.println("Print in asc order before reservation");
//        list.display(true);
//        System.out.println("Print in asc order after reservation");
//        list.reverse();
//        list.display(true);
//        System.out.println("----------------------------");
//        System.out.println("---> Removal <---");
//        System.out.println("Remove first element");
//        list.remove();
//        System.out.println("Remove last element");
//        list.pop();
//        System.out.println("Remove element in index 4");
//        list.remove(6);
//        System.out.println("Size : " + list.capacity());
//        System.out.println("Print in asc order");
//        list.display(true);
//        System.out.println("----------------------------");
//        System.out.println("---> Reset <---");
//        System.out.println("Clear list");
//        list.clear();
//        System.out.println("Is empty : " + list.isEmpty());
//        System.out.println("Size : " + list.capacity());
//        System.out.println("Print in asc order");
//        list.display(true);
    }
}